[package]
name = "binary2d"
version = "0.1.0"
authors = ["Jonathan Zrake <jonathan.zrake@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num             = "0.3"
ndarray         = "0.13"
hdf5            = "0.7"
kind-config     = "0.2"

kepler-two-body = { git = "https://github.com/clemson-cal/kepler-two-body" }
hydro-iso2d     = { git = "https://github.com/clemson-cal/hydro-iso2d" }
godunov-core    = { git = "https://github.com/clemson-cal/godunov-core" }
ndarray-ops     = { path = "ndarray-ops" }

[profile.release]
lto = true
